---
name: Release Executables

permissions:
  contents: read
  pull-requests: write

on:
  push:
    tags:
      - '*'

# https://hynek.me/articles/python-github-actions/
jobs:

  # 1. Release Windows Executable
  #
  release-windows-exe:
    name: 'script.exe release for Windows'
    needs: build-windows-exe
    runs-on: 'windows-latest'
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: strat-select-win.exe
      # copy nicks-script.exe to the release
      # https://github.com/marketplace/actions/upload-files-to-a-github-release
      - name: upload executable to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: strat-select-win.exe
          tag: ${{ github.ref }}
          overwrite: true
          body: "script release text"

  # 2. Release MacOS Executable
  #
  release-macos-executable:
    name: 'script.app release for MacOS'
    needs: build-macos-executable
    runs-on: 'macos-latest'
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: strat-select-macos
      # copy script.app to the release
      # https://github.com/marketplace/actions/upload-files-to-a-github-release
      - name: upload exectuable to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: strat-select-macos
          tag: ${{ github.ref }}
          overwrite: true
          body: "script release text"

  # 3. Release Linux Executable
  #
  release-linux-executable:
    name: 'executable release for Linux'
    needs: build-linux-executable
    runs-on: 'ubuntu-24.04'
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: strat-select-linux
      # copy script.app to the release
      #
      # https://github.com/marketplace/actions/upload-files-to-a-github-release
      - name: upload exectuable to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: strat-select-linux
          tag: ${{ github.ref }}
          overwrite: true
          body: "script release text"
