---
name: Release Executables

permissions:
  contents: read
  pull-requests: write

on:
  push:
    tags:
      - '*'

# https://hynek.me/articles/python-github-actions/
jobs:
  #
  # 1. Build Windows Executable
  #
  build-windows-exe:
    name: 'script.exe creation using python 3.11 on Windows'
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.2"
          python-version: '3.11'
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: "Install dependencies"
        run: |
          uv run python -VV
          uv run python -m site
          uv sync
      - name: "Build windows package"
        run: |
          uv run python -m eel script.py web -n strat-select-win.exe --additional-hooks-dir=. --onefile
          mkdir -p target/release
          mv dist/strat-select-win.exe target/release
      # copy nicks-script.exe to the release
      # https://github.com/marketplace/actions/upload-files-to-a-github-release
      - name: upload executable to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/strat-select-win.exe
          tag: ${{ github.ref }}
          overwrite: true
          body: "script release text"
  #
  # 2. Build MacOS Executable
  #
  build-macos-executable:
    name: 'script.app creation using python 3.11 on MacOS'
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.2"
          python-version: '3.11'
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: "Install dependencies"
        run: |
          uv run python -VV
          uv run python -m site
          uv sync
      - name: "Build MacOS package"
        run: |
          uv run python -m eel script.py web -n strat-select-macos --additional-hooks-dir=. --onefile
          mkdir -p target/release
          mv dist/strat-select-macos target/release
      # copy script.app to the release
      # https://github.com/marketplace/actions/upload-files-to-a-github-release
      - name: upload exectuable to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/strat-select-macos
          tag: ${{ github.ref }}
          overwrite: true
          body: "script release text"
  #
  # 3. Build Linux Executable
  #
  build-linux-executable:
    name: 'executable creation using python 3.11 on Linux'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.2"
          python-version: '3.11'
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: "Install dependencies"
        run: |
          uv run python -VV
          uv run python -m site
          uv sync
      - name: "Build Linux package"
        run: |
          uv run python -m eel script.py web -n strat-select-linux --additional-hooks-dir=. --onefile
          mkdir -p target/release
          mv dist/strat-select-linux target/release
      # copy script.app to the release
      #
      # https://github.com/marketplace/actions/upload-files-to-a-github-release
      - name: upload exectuable to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/strat-select-linux
          tag: ${{ github.ref }}
          overwrite: true
          body: "script release text"
